alias ra='ranger'
alias c='clear'
alias gad='git add'
alias gcm='git commit'
alias gst='git status'
alias glog='git reflog'
alias gco='git checkout'
alias gremote='git remote'
alias gbr='git branch'
alias vim='nvim'
alias copy_to_remote='sudo cp ~/.config/fish/config.fish ~/gitRep/Code/etc/config.fish;sudo cp ~/.config/nvim/init.vim ~/gitRep/Code/etc/init.vim;sudo cp ~/.config/ranger ~/gitRep/Code/etc/ranger -r;sudo cp ~/.config/nvim/coc-settings.json ~/gitRep/Code/etc/coc-settings.json'
alias copy_to_local='sudo cp ~/gitRep/Code/etc/config.fish ~/.config/fish/config.fish ;sudo cp ~/gitRep/Code/etc/init.vim ~/.config/nvim/init.vim;sudo cp ~/gitRep/Code/etc/ranger ~/.config/ranger -r;sudo cp ~/gitRep/Code/etc/coc-settings.json ~/.config/nvim/coc-settings.json'

set -g -x RANGER_LOAD_DEFAULT_RC FALSE
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
